name: evntas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.6.0"
  flutter: "3.27.1"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  go_router: 13.0.0
  flutter_svg: 2.0.0
  fluttertoast: 8.2.12
  flutter_screenutil: 5.9.0
  google_fonts: 6.1.0 # For custom fonts
  intl: 0.19.0
  supabase_flutter: 2.8.3
  google_sign_in: 6.3.0
  cached_network_image: 3.4.1
  firebase_core: 3.13.0
  firebase_messaging: 15.2.5
  cloud_firestore: 5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/
    - assets/images/
