name: hello_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.5.3"
  flutter: "3.24.3"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  go_router: 13.0.0
  flutter_svg: 2.0.0
  fluttertoast: 8.1.2
  flutter_screenutil: 5.9.0
  google_fonts: 6.1.0 # For custom fonts
  intl: 0.19.0
  supabase_flutter: 2.8.3
  image_picker: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/
    - assets/images/
