name: domain
description: "Domain Layer"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: 2.0.2 # For pretty logging
  flutter_dotenv: 5.1.0
  google_sign_in: 5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
